### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by shashankmanjunath** [blairtyx/EC601#2]
Hi @blairtyx,

This repo (project 2) is very interesting, and contains some robust code! However, the Readme needs a few updates (https://github.com/blairtyx/EC601/blob/master/Project2/README.md and Readmes in subdirectories):

1. The Readme needs to explain the project. After reading the Readme, I'm left asking what function the project fulfills. What user story does the project address?
2. The Readme needs to cover the Twitter and Google API in a more thorough manner. While the framework to explain the API included in this project is there, but needs to be fleshed out
3. The error handling needs to be more specific. If a situation occurs (such as the addressed "wrong handle" situation - instead of stating that the code handles the situation, a better explanation would be how the code handles the situation and why or why not an error is returned).

Please let me know if you have any questions. Thanks!

**Comment by blairtyx** [comment]
Hi, thanks a lot for these comments. I'm working on the README.md to improve the user experience. Thanks
