### ISSUE TITLE
Add additional options to your retweets user input options

### ISSUE THREAD

**Issue by JakeHellman** [blairtyx/EC601#6]
Right now the retweets user input section will accept the following inputs:

`rts_list_1 = ['1', 'True', 'true', 'TRUE','yes', 'YES']`
`rts_list_0 = ['0', 'False', 'false','FALSE', 'no', 'NO']`

I believe that "Yes" and "No" are likely options. Please add these to the list of acceptable options.

Additionally, the user is prompted to enter "\<true>" or "\<false>" so I propose that these two options should be added to the list as well.

**Comment by blairtyx** [comment]
Hi, thanks a lot! I'll modify the input section.
